### ISSUE TITLE
RenameTestCases now capitalizes in a couple unexpected places

### ISSUE THREAD

**Issue by KleerCoder** [MarketSquare/robotframework-tidy#545] opened 2023-06-28 00:02 UTC
I am attempting to update our repositories to support Robotidy 4.3.0 (we currently use 3.2.0) and I see some changes being made to the **test case** names. My understanding is that words inside parentheses should now be capitalized, which I see and it looks good, but there are also some other changes:

Ex. 1: `Select 3rd Option` becomes `Select 3Rd Option`
Ex. 2: `With 1200x950` becomes `With 1200X950 `(this isn't a big deal, but I do find the original more readable)
Ex. 3: `Open 3-dot Menu `becomes `Open 3-Dot Menu `(I'm not concerned about this one, but I figured I'd note the example)

**Comment by bhirsz** [comment] 2023-06-28 05:00
Thanks for the report, I see where the problem is. I will fix it

**Comment by bhirsz** [comment] 2023-06-28 10:05
Fixed - it will be released in 4.4.0 today.

**Closed** 2023-06-28 10:04 UTC
