### ISSUE TITLE
OrderTags does not honor line-length setting

### ISSUE THREAD

**Issue by jylind** [MarketSquare/robotframework-tidy#455] opened 2023-01-17 19:21 UTC
Robot Framework = 6.0.2
Robot Tidy = 3.3.2

RoboTidy is getting configuration from `pyproject.toml`. There we have set the `line-length` to `120`.
Following happens:
Line
```
    [Tags]    PS_CSMON_15838    PR_PPD    PR_B450    PR_B650    PR_B850    PR_CS1000    PR_CS1000L
        ...    PAR_ECG    PAR_IP_1    PAR_SPO2
```

Is formatted to:
```
    [Tags]    PAR_ECG    PAR_IP_1    PAR_SPO2    PR_B450    PR_B650    PR_B850    PR_CS1000    PR_CS1000L    PR_PPD    PS_CSMON_15838
```
line length being now 134.

Then we run RFLint and it will fail because it does not allow anything to be longer than 120

**Comment by jylind** [comment] 2023-01-17 20:44
I would expect transformer `SplitTooLongLine` to pick this up, at least on the next run.

But is it so that it is only run for `keyword calls or variables`

In my opinion, all suite settings (except documentation maybe) and test/keyword "settings" (like [Tags]) should be checked for long lines.

**Comment by bhirsz** [comment] 2023-01-17 21:06
You're right, SplitTooLongLine should also work on settings. It's not a bug but missing feature - like you noticed it was designed to work on keyword calls only. Recently it was expanded to also work with variables. And we definietly need to make it work with all possible types (like settings, tags). 

And while some transformers also handle splitting too long lines I usually prefer to keep them independent. That's why it should be fine that order tags add everything to one line but then SplitTooLongLine should "fix it". 

And check out RoboCop for linting if you dont know it already :)

**Comment by jylind** [comment] 2023-01-18 10:10
Thanks for the reply.
Maybe having one transformer to do all the splitting of long lines is fine and maybe simple to implement but I do think that requirement should be that you only need to run robotidy once per file to get the final result.

We have already noticed that for some cases robotidy must be executed twice before you get what you want. This is confusing to the user, and it is not that convenient.

Let say you are using pre-commit tool and you would need to run git commit command three times to get robotidy pass and get the commit completed.
I’m looking at robotidy as being a similar tool as what the black is for python. And it fixes everything with one run.

Taking a look at robocop is in out backlog. We have been using RFLint for quite some time and we have created quite a few custom linting rules for it. Before we could move to robocop we would need to have similar linting rules created for robocop as well.

**Comment by bhirsz** [comment] 2023-01-18 10:27
It's the blessing of the Robotidy which became our curse :) So the goal was to be able to freely configure anything (for example you may want to split the too long lines, but do not order tags etc). That's why you can disable/enable particular transformers or configure them. In that sense black is simpler since it doesn't allow that much configuration and just runs predefined transformations. However it's suitable for Python (less time wasted on code styling discussions). This architecture forces us to make transformers more independent and run them in a specific order. Sometimes transformer that runs in the end changes the syntax so much, that we require to rerun the robotidy so the earlier transformer can "fix" the code again until it stabilizes.

But one of my main goals is closing this gap a little and like you described - to only run robotidy once to get a stable result.  It can be achieved through many ways - either by one transformer doing additional formatting or by internal logic that would rerun the formatting once or twice until the result doesn't change. In this particular case I'm thinking of two things:

- I will of course update SplitTooLongLine transformer to split settings,
- I will update OrderTags to be aware of line length. It should be simple to do as I have prepared some 'backend' mehtods for this (I have already done this for aligner transformers)

The only problem I need to think about is how to split such settings. I will probably reuse "split_on_every_arg" setting from SplitTooLongLine but in a long list of tags it will create multiline blocks:
```
 [Tags]  tag1
...  tag2
...  tag3
...  tag4
```
Probably users would want to tags to "fill until line limit" and keyword args to "split on every arg" so I will need separate parameter to control it.

**Comment by jylind** [comment] 2023-01-18 10:43
All this sounds good to me.
And yes, my personal preference here (and maybe with some other transformers) would be `fill-until-line-limit` 😀

**Comment by bhirsz** [comment] 2023-02-15 11:25
I've just returned from the break and I'm back to the topic. I have decided to update SplitTooLongLine transformer so it does split the settings . For now it does split any kind of tags (Force Tags, [Tags]..) and arguments ([Arguments]). The support for the remaining settings (such as [Setup], [Template]..) will be implemented later. It should be part of the next release - hopefully by the end of the week. 

The implementation splits settings to every line by default. 

Original:
```
[Tags]    PAR_ECG    PAR_IP_1    PAR_SPO2    PR_B450    PR_B650    PR_B850    PR_CS1000    PR_CS1000L    PR_PPD    PS_CSMON_15838
```

Default output of the SplitTooLongLine:
```
    [Tags]
    ...    tag
    ...    tag
    ...    PS_CSMON_15838
    ...    PR_PPD
    ...    PR_B450
    ...    PR_B650
    ...    PR_B850
    ...    PR_CS1000
    ...    PR_CS1000L
    ...    PAR_ECG
    ...    PAR_IP_1
    ...    PAR_SPO2
```

It is possible to use new parameter ``split_on_every_setting_arg`` to "fill-until-line-limit":

robocop -c SplitTooLongLine:split_on_every_setting_arg=False <src>
```
    [Tags]    PS_CSMON_15838    PR_PPD    PR_B450    PR_B650    PR_B850    PR_CS1000    PR_CS1000L    PAR_ECG
    ...    PAR_IP_1    PAR_SPO2
```

It is possible to skip splitting settings by using skip_settings (either globally with --skip-settings or -c SplitTooLongLine:skip_settings=True) or with particular skip like skip_tags. 

The only caveat is that we don't handle comments well. Any comment found in the setting will be moved after the setting:
```
Test with comments in settings
    [Tags]    tag    # comment1
    ...    tag  # comment2
    ...    PS_CSMON_15838    PR_PPD    PR_B450    PR_B650    PR_B850    PR_CS1000    PR_CS1000L    PAR_ECG    PAR_IP_1    PAR_SPO2   # comment3
```
to
```
Test with comments in settings
    [Tags]    tag    tag    PS_CSMON_15838    PR_PPD    PR_B450    PR_B650    PR_B850    PR_CS1000    PR_CS1000L
    ...    PAR_ECG    PAR_IP_1    PAR_SPO2
    # comment1
    # comment2
    # comment3
```

But SplitTooLongLine will only touch the setting if it's not in the line limit. If you manually update the code, add comments and the the line is under allowed length (or you're using skip_comments to not count comment length), it will not format the setting. So the comments will be preserved.

**Closed** 2023-02-16 11:45 UTC
