### ISSUE TITLE
Disabler not working for "Test Tags" setting.

### ISSUE THREAD

**Issue by gohierf** [MarketSquare/robotframework-tidy#639] opened 2024-02-21 12:29 UTC
`# robotidy: off` disabler does not work on the `Test Tags` setting.

Here is the expected result (disabler works when used on `*** Settings ***` line or first line of the file).
![disabler_setting_line](https://github.com/MarketSquare/robotframework-tidy/assets/33861657/47def6eb-99f0-4f68-93fe-8b68659018f4)

Here is robotidy result with the disabler on the same line as `Test Tags`:
BEFORE:
![disabler_test_tags_line_before](https://github.com/MarketSquare/robotframework-tidy/assets/33861657/7ee2c7b4-3a9a-4ac5-8798-23ba5922c719)

AFTER:
![disabler_test_tags_after](https://github.com/MarketSquare/robotframework-tidy/assets/33861657/44a6ffd7-f8fe-4aec-bedb-b2e5fe2ed023)

Here is the result with the disabler on the previous line.
BEFORE:
![disabler_prev_line_before](https://github.com/MarketSquare/robotframework-tidy/assets/33861657/b3186e85-826b-49d9-8e03-dde075965249)

AFTER:
![disabler_prev_line_after](https://github.com/MarketSquare/robotframework-tidy/assets/33861657/284d09ec-e88b-4ded-b878-a10915a279c7)

Note that a side effect of using the disabler on the  `Test Tags` line or the previous line, is that the output line is too long.
Which does not happen without any disabler:
![disabler_none](https://github.com/MarketSquare/robotframework-tidy/assets/33861657/270065ab-c201-48a3-8433-2c094fe856c2)

**Comment by bhirsz** [comment] 2024-02-27 16:59
It required some extensive debugging but I've discovered that ``OrderSettings`` transformer does modify ``end_lineno`` attribute of the ``TestTags`` node. It then affects disabler logic - node is not considered disabled. 

I will track why ``OrderSettings`` does that, but I have simple workaround for now too - when checking if the node is disabled, I can at least set ``end_lineno = -1`` to ``lineno`` value. It should help with most of the cases.

**Comment by bhirsz** [comment] 2024-02-27 17:15
Implemented workaround and fixed root cause - it will be part of the next release.

**Closed** 2024-02-27 17:25 UTC
Labels: bug
