### ISSUE TITLE
Running Robotidy Sometimes Results in Inconsistent New Lines

### ISSUE THREAD

**Issue by katjie** [MarketSquare/robotframework-tidy#236] opened 2021-12-10 08:42 UTC
robotframework-tidy version 1.6.2

If I run robotidy on the attached file (in my case, done by saving Ctrl+S on VS Code using robotframework-lsp extension) I get an inconsistent spacing between the keywords and test cases when I hit save a few times (without other changes):

Here there is one line spacing:
![image](https://user-images.githubusercontent.com/19191177/145543346-85ffba06-9ba2-4c4a-bc25-792b0a92ff6d.png)

Here there is two line spacing (I have not changed anything in the file, just hit save on VS Code twice):
![image](https://user-images.githubusercontent.com/19191177/145543447-b5aea727-8133-4753-b1b1-9097857266f4.png)

In my pyproject.toml, my settings are as follows:
`[tool.robotidy]
src = [
    "."
]
configure = [
    "NormalizeAssignments:equal_sign_type=remove",
    "MergeAndOrderSections:order=comments,settings,variables,keywords,testcases",
    "RenameKeywords:enabled=True",
    "NormalizeNewLines=True"
]`

Perhaps I have something wrong in my configuration, but maybe it is still a bug that different runs of robotidy on the same file can result in different outputs.

Here is the file I am running on (as .txt because github does not let me upload .robot :D )
[robotidy.txt](https://github.com/MarketSquare/robotframework-tidy/files/7691288/robotidy.txt)

**Comment by bhirsz** [comment] 2021-12-10 08:58
Thank you for the report. I cannot reproduce it right now (except the issue that if the file wasn't changed by tidy it shouldn't be saved on the disk). Hovewer I will try to test it with VS Code in case it's somehow connected. 

You config is okay (spare the missing parameter name in `NormalizeNewLines=True` -> `NormalizeNewLines:enabled=True`).

**Comment by katjie** [comment] 2021-12-13 09:28
I have tried it myself now and can confirm that running robotidy from command line cannot reproduce this bug, so it does seem likely that it is maybe connected with VS Code and/or maybe robotframework-lsp extension that I am using to format on save.

**Comment by bhirsz** [comment] 2022-02-03 13:15
If you can - open issue in lsp repository but link it there. This could be something on our side (like an our API that LSP is using). Right now I'm going over open issued and implementing them - so I will reach to this issue at some point and I will try to check it. In meantime there is chance that robotframework-lsp devs will find the root cause.

**Comment by katjie** [comment] 2022-02-03 13:43
@bhirsz I was looking at this a lot today so I already have "fixed" it - turns out that I never set the "lineseparator" option, so it was overriding my .robot files, which were saved as LF (unix), with CRLF (native). 

I can imagine the problem came up with robotidy converting the file to CRLF line endings, and then VS Code (due to my own configuration) converting it back to LF (or something like that, since I am not sure how VS Code handles line endings and format on save). 

Now that I have set the "lineseparator" option to unix, I cannot see the issue anymore when saving through VS Code.

**Comment by bhirsz** [comment] 2022-02-03 20:16
Thanks for the testing it. So do you think it's not a bug but just missing configuration? Or robotidy should handle lineseparator better? (there is also `auto` option for it instead of setting it fixed).

**Comment by bhirsz** [comment] 2022-03-24 08:32
Closing as it doesn't appear as bug on our side - feel free to comment if you disagree.

**Closed by bhirsz** 2022-03-24 08:32 UTC
Labels: bug
