### ISSUE TITLE
Incorrect alignment - AlignTemplatedTestCases and [Tags]

### ISSUE THREAD

**Issue by Zeckie** [MarketSquare/robotframework-tidy#443] opened 2022-11-16 06:41 UTC
When `[Tags]` is on the same line as the test case name in [data-driven style](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#data-driven-style) tests, and `AlignTemplatedTestCases` is enabled, robotframework-lint applies incorrect indentation. It looks like it is not subtracting the length of the test case name from the number of required spaces.

```robotframework
*** Settings ***
Test Template       Login with invalid credentials should fail

*** Test Cases ***                  USERNAME            PASSWORD
Invalid User Name                   [Tags]              foo
                                    invalid             ${VALID PASSWORD}
Invalid Password
                                    [Tags]              bar
                                    ${VALID USER}       invalid
Invalid User Name and Password      [Tags]              baz
                                    invalid             invalid
Empty User Name                     ${EMPTY}            ${VALID PASSWORD}
Empty Password                      ${VALID USER}       ${EMPTY}
                                    [Tags]              spam  eggs
Empty User Name and Password        ${EMPTY}            ${EMPTY}


*** Keywords ***
Login With Invalid Credentials Should Fail
    [Arguments]    ${username}    ${password}
```

is changed to:

```robotframework
*** Settings ***
Test Template       Login with invalid credentials should fail


*** Test Cases ***                  USERNAME            PASSWORD
Invalid User Name                                    [Tags]              foo
                                    invalid             ${VALID PASSWORD}
Invalid Password
                                    [Tags]              bar
                                    ${VALID USER}       invalid
Invalid User Name and Password                                    [Tags]              baz
                                    invalid             invalid
Empty User Name                     ${EMPTY}            ${VALID PASSWORD}
Empty Password                                    [Tags]              spam                    eggs
                                    ${VALID USER}       ${EMPTY}
Empty User Name and Password        ${EMPTY}            ${EMPTY}


*** Keywords ***
Login With Invalid Credentials Should Fail
    [Arguments]    ${username}    ${password}
```

**Comment by bhirsz** [comment] 2022-12-04 19:58
Thanks for the report, I will investigate this

**Comment by bhirsz** [comment] 2023-01-09 17:38
Sorry for the delay. 

At beginning I couldn't reproduce it when running ``AlignTemplatedTestCases`` alone. Turns out this issue only happens when executing more than one transformer (and most of our acceptance tests run in isolation from other transformers). It will be fixed in the next release (out in the next few days - week). Below I include more detailed information about the issue but this is more for documentation purpose.

When robotidy reads the file to tokens, we're serializing it into Python classes like Token(Tags, ..). It also contains extra information like line numbers, columns etc. This information was used by ``AlignTemplatedTestCases`` to determine if given statement (like test argument or tags settings) is on the same line as test case name. If it was, the test case name length was deducted from the expected column alignment width. Hovewer other transformer - ``NormalizeTags``- recreate any found Tags object. Whenever we recreate token without saving whole model to file and reading it back, we are losing some of the metada such as line number. And that's why in your case ``NormalizeTags`` first recreated tags and made it impossible for ``AlignTemplatedTestCases`` to correctly determine if given line was in the same line as test case name. The best solution for this would be reloading whole model after (re)creating any new token class in the model but it would be too big performance hit. That's why I've decided to:

- change the way ``AlignTemplatedTestCases`` is given line is in the same line as test case name (now I'm simply checking if last encountered test case name ended with end of line character). This is enough to fix this issue,
- update ``NormalizeTags`` so it does not recreate whole tags if there is no need to (usually tags before and after normalization are the same, so we don't need to recreate tags). This will be separate update.

**Closed** 2023-01-15 16:19 UTC
