### ISSUE TITLE
Alignment keywords use `min_width` in a confusing way

### ISSUE THREAD

**Issue by Lakitna** [MarketSquare/robotframework-tidy#558] opened 2023-08-15 10:39 UTC
Given the following snippet of variables

```robot
*** Variables ***
${aVeryLongVariableNameIsSuperLongToHighlightAlignment}  suchLong
${foo}  bar
${lorum}  ipsum
```

If I format with the following setting:
```toml
configure = [
    "AlignVariablesSection : min_width = 0",
]
```

It produces the following

```robot
*** Variables ***
${aVeryLongVariableNameIsSuperLongToHighlightAlignment}     suchLong
${foo}                                                      bar
${lorum}                                                    ipsum
```

As expected, it aligns everything to match the longest variable name.

---

However, if I format with the following setting:
```toml
configure = [
    "AlignVariablesSection : min_width = 1",
]
```

It produces the following

```robot
*** Variables ***
${aVeryLongVariableNameIsSuperLongToHighlightAlignment}    suchLong
${foo}    bar
${lorum}    ipsum
```

It just lost all alignment and I did not expect that.

---

A similar thing happens when I raise the min width:
```toml
configure = [
    "AlignVariablesSection : min_width = 20",
]
```

It produces the following

```robot
*** Variables ***
${aVeryLongVariableNameIsSuperLongToHighlightAlignment}    suchLong
${foo}              bar
${lorum}            ipsum
```

It's almost like `min_width` is accidentally implemented as `exact_width_unless_previous_column_is_too_long`.

I have observed the same behavior in `AlignSettingsSection`. I have not checked other alignment transformers.

Python version: 3.10
Robot version: 4.1.3
Robotidy version: 4.4.0

**Comment by bhirsz** [comment] 2023-08-15 20:57
Thanks for the report, I will take a look. Instictively looking it should align whole column to max(min_width, longest_token) but it does not looking at your examples.

**Comment by bhirsz** [comment] 2023-08-15 21:06
I didnt run it yet but I see in the code that you're right. It uses exact min_width (unless token is longer than min_width) instead of using the longest token length for whole column.

I'm not even sure what I was thinking by creating this code :) Most likely because old tidy used fixed width for alignment and I reused the approach. I will fix it though I hope others dont rely on this behaviour (if they do, I can introduce extra optional fixed alignment parameter).

**Comment by bhirsz** [comment] 2023-08-16 07:12
I will add new parameter "fixed_width" (which will be doing exactly what "min_width" is currently doing) and change logic for "min_width" to work as intended. While technically a fix, it will be part of the next feature release (4.5.0) once PR is up and merged  because of the new parameter.

**Closed** 2023-08-21 07:28 UTC
