### ISSUE TITLE
[Bug] Transformer/configuration not being honored after disabled code block

### ISSUE THREAD

**Issue by Ga22be** [MarketSquare/robotframework-tidy#479] opened 2023-03-03 10:49 UTC
Using following config:

```toml
[tool.robotidy]
target-version = "rf4"
overwrite = true
diff = false
spacecount = 4
continuation-indent = 4
line-length = 80
skip_documentation = true
transform = [
    "AddMissingEnd",
    "AlignSettingsSection",
    "AlignVariablesSection",
    "DiscardEmptySections",
    "IndentNestedKeywords",
    "MergeAndOrderSections",
    "NormalizeAssignments",
    "NormalizeNewLines",
    "NormalizeSectionHeaderName",
    "NormalizeSeparators",
    "NormalizeSettingName",
    "OrderSettings",
    "OrderSettingsSection",
    "RemoveEmptySettings",
    "RenameKeywords",
    "RenameTestCases",
    "ReplaceRunKeywordIf",
    "SplitTooLongLine"
]
configure = [
    "AlignKeywordsSection:alignment_type=auto",
    "AlignKeywordsSection:handle_too_long=compact_overflow",
    "AlignSettingsSection:up_to_column=0",
    "AlignSettingsSection:skip_tags=True",
    "AlignTestCasesSection:alignment_type=auto",
    "AlignTestCasesSection:handle_too_long=compact_overflow",
    "AlignVariablesSection:up_to_column=0",
    "DiscardEmptySections:allow_only_comments=True",
    "NormalizeAssignments:equal_sign_type=space_and_equal_sign",
    "NormalizeSeparators:sections=testcases,keywords",
    "NormalizeSeparators:skip_comments=True",
    "NormalizeTags:normalize_case=False",
    "RenameTestCases:capitalize_each_word=True",
    "SplitTooLongLine:skip_comments=True",
]
```

... and following code:

```robotframework
# robotidy: off
# robotidy: on

*** Test Cases ***
A test case name for formatting and POC purpose
    Run Keyword If    '${FOO}'=='BAR'    Set Tags    TransformToIFAndIndent

*** Keyword ***
If I dont include this keyword the behaviour changes

```

I expect something like the following formatting:

```robotframework
*** Comments ***
# robotidy: off
# robotidy: on


*** Test Cases ***
A Test Case Name For Formatting And POC Purpose
    IF    '${FOO}'=='BAR'
        Set Tags    TransformToIFAndIndent
    END


*** Keywords ***
If I Dont Include This Keyword The Behaviour Changes
```

... but I get the following:

```robotframework
*** Comments ***
# robotidy: off
# robotidy: on


*** Test Cases ***
A test case name for formatting and POC purpose
    Run Keyword If    '${FOO}'=='BAR'
    ...    Set Tags    TransformToIFAndIndent


*** Keywords ***
If I Dont Include This Keyword The Behaviour Changes

```

**_NOTE:_** The original code is much larger and that this is a shrunken down PoC. Originally the disabled block contained all my variables. I have kept the configuration as is though.

**Description**
If I remove the disablers in the beginning of the code robotidy formats as expected, but as soon as I add the disablers robotidy seemingly starts ignoring some of my transformers and configuration OUTSIDE of the disabled block. This feels like a bug. But it seems that anything before the disablers is unaffected and works as expected.

**Comment by bhirsz** [comment] 2023-03-14 15:10
It is by design - if you put the disabler in the first line of file it will ignore the rest of the file. But I agree it does not look like something we would expect (especially if we define enabler). 

I will update the code do the rest of the file is always checked for possible enablers. 

It's different matter if you define disabler in the middle of the file and it affect the lines it shouldnt - if that's the case, I will also investigate it

**Comment by bhirsz** [comment] 2023-03-14 19:39
I have discovered some problem with disablers in general - I see that putting disabler/enabler right in the section disables some transformers. I'm working on it

**Comment by bhirsz** [comment] 2023-03-15 10:17
The problem originate from the ``NormalizeNewLines``. Whenever we recreate nodes, or move them, the metadata info that is created when loading the Robot code model like lineno, end_lineno is lost (for example if the original lineno is 11, it will be -1 after recreating the node). The disablers use lineno to see if it does match any known disabler - and since recreated nodes will have "-1" lineno, it will always match. 

In this issue I will for sure:
  - update the disabler logic so # robocop: off in the first line do not disable whole file if there is enabler somewhere
 
What I still consider:
  - The model metadata is loaded when we reload the whole model again. I can do it after every transformer - I actually did some POC and it works and this issue is fixed. However it has huge impact on performance
  - I can also try to redesign some of the transformers that recreate/change nodes so much that the lines metadata changes. For example ``NormalizeNewLines`` always remove empty lines (losing metadata), and then recreates them. Instead it maybe could only add/remove lines if needed. It is more work but it does not affect performance

**Comment by bhirsz** [comment] 2024-02-27 17:36
The original issue from the thread should be already fixed. I will also release additional fixes related to the disablers in next releases - we will see if it stabilize situation. Closing the issue

**Closed by bhirsz** 2024-02-27 17:36 UTC
